# Generated by Django 5.2.15 on 2026-08-21 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_title', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificates/logos/')),
                ('organization_name', models.CharField(max_length=200)),
                ('certificate_body', models.TextField()),
                ('signature_name', models.CharField(blank=True, max_length=150)),
                ('signature_designation', models.CharField(blank=True, max_length=150)),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
