# Generated by Django 5.2.15 on 2026-08-21 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_certificatetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('pass_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('certificate_content', models.TextField(blank=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('course_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='students.courseenrollment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='students.student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='students.certificatetemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
